# Generated by Django 2.2.12 on 2020-08-29 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200829_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikes',
            name='date_liked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='like_dislike',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')]),
        ),
        migrations.AlterUniqueTogether(
            name='userlikes',
            unique_together={('user', 'post', 'like_dislike')},
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='vote_type',
        ),
    ]
