# Generated by Django 2.2.12 on 2020-08-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200829_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
