# Generated by Django 2.2.12 on 2020-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200831_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='date_liked',
            field=models.DateField(auto_now=True),
        ),
    ]
